package resource;

/**
 * テストに出す英単語と意味(日本語訳)を保持するクラス
 * @author kkiku
 */
public class WordsAndMeanings {
	// 英単語
	public static String[] words = { "", "improve", "relate", "provide", "consider", "include", "concern", "involve",
			"produce", "allow", "require", "appear", "tend", "agree", "describe", "add", "depend", "encourage", "exist",
			"reduce", "adapt", "compare", "increase", "suggest", "cost", "share", "wonder", "argue", "realize",
			"control", "affect", "find", "notice", "avoid", "force", "offer", "demand", "claim", "deal", "store",
			"complete", "value", "benefit", "opportunity", "quality", "author", "technology", "environment", "view",
			"situation", "effect", "influence", "term", "skill", "theory", "issue", "subject", "article", "statement",
			"experiment", "figure", "evidence", "industry", "economy", "medicine", "matter", "material", "species",
			"practice", "focus", "memory", "right", "accord", "thought", "interest", "account", "cause", "sound",
			"individual", "certain", "possible", "likely", "available", "social", "public", "physical", "scientific",
			"common", "general", "particular", "similar", "various", "native", "patient", "recent", "even", "yet",
			"rather", "instead", "simultaneously", "each", "challenge", "determine", "manage", "maintain", "refer",
			"approach", "advance", "express", "spread", "occur", "observe", "recognize", "suppose", "regard", "treat",
			"search", "prove", "establish", "mention", "represent", "prefer", "apply", "seek", "publish", "perform",
			"gain", "fit", "contain", "supply", "prepare", "bear", "prevent", "object", "decline", "replace", "connect",
			"attend", "survive", "respect", "waste", "advantage", "resource", "medium", "method", "attitude",
			"structure", "function", "feature", "aspect", "content", "detail", "range", "region", "trade", "habit",
			"cell", "fuel", "bill", "charge", "fine", "temperature", "decade", "emotion", "explanation", "solution",
			"degree", "access", "contrast", "status", "surface", "conflict", "audience", "clay", "epoch", "profit",
			"income", "ancestor", "crop", "significant", "necessary", "appropriate", "correct", "worth", "positive",
			"plastic", "political", "official", "private", "ancient", "due", "complex", "mobile", "blank", "male",
			"therefore", "thus", "eventually", "otherwise", "despite", "both", "succeed", "identify", "reflect",
			"assume", "estimate", "define", "indicate", "reveal", "attempt", "respond", "associate", "examine",
			"address", "trust", "doubt", "ignore", "refuse", "complain", "decrease", "vary", "emerge", "match", "stick",
			"hide", "attract", "promote", "satisfy", "earn", "preserve", "enable", "destroy", "tear", "suffer",
			"survey", "divide", "conduct", "graduate", "contribute", "desire", "relax", "target", "aim", "principle",
			"norm", "strategy", "track", "progress", "personality", "characteristic", "manner", "device", "origin",
			"gene", "atmosphere", "trend", "phenomenon", "context", "circumstance", "pain", "struggle", "pollution",
			"threat", "disaster", "consequence", "revolution", "majority", "mass", "stock", "wealth", "literature",
			"authority", "institution", "custom", "sight", "display", "colleague", "resident", "vehicle", "essential",
			"aware", "mental", "academic", "ordinary", "familiar", "novel", "specific", "chemical", "financial",
			"active", "negative", "direct", "obvious", "current", "urban", "furthermore", "likewise", "though",
			"nevertheless", "thereby", "hence", "appreciate", "admit", "predict", "acquire", "adopt", "purchase",
			"afford", "consume", "remove", "suit", "expand", "extend", "explore", "judge", "demonstrate", "insist",
			"appeal", "convince", "settle", "aid", "educate", "engage", "combine", "organize", "operate", "recall",
			"rely", "amaze", "confuse", "blame", "criticize", "behave", "encounter", "select", "flow", "evolve",
			"freeze", "release", "locate", "advertise", "imagination", "perspective", "confidence", "achievement",
			"reward", "corporation", "capital", "client", "crisis", "harm", "victim", "option", "campaign", "court",
			"code", "criminal", "agriculture", "religion", "philosophy", "conference", "document", "statistics",
			"analysis", "hypothesis", "notion", "stereotype", "review", "vocabulary", "organ", "gender", "fossil",
			"glacier", "laboratory", "virus", "occasion", "minister", "presence", "substance", "creative", "potential",
			"independent", "willing", "efficient", "ideal", "genetic", "entire", "relative", "extreme", "vast", "tiny",
			"desert", "rural", "previous", "legal", "nowadays", "seldom", "meanwhile", "latter", "versus", "all",
			"perceive", "expect", "intend", "request", "remind", "inspire", "fascinate", "emphasize", "recommend",
			"propose", "distinguish", "complicate", "transform", "credit", "reserve", "oppose", "deny", "reject", "ban",
			"frighten", "participate", "compete", "overcome", "arise", "generate", "obtain", "employ", "import",
			"handle", "repair", "cure", "transport", "deliver", "rush", "commit", "hate", "regret", "consist",
			"translate", "conclude", "comfort", "facility", "trait", "humanity", "tribe", "elite", "lawyer", "category",
			"version", "diversity", "proportion", "instrument", "innovation", "weapon", "dialect", "barrier", "myth",
			"ritual", "routine", "emergency", "alarm", "harvest", "grain", "quantity", "budget", "expense", "insurance",
			"loan", "contract", "mammal", "infant", "protein", "tissue", "fault", "neighborhood", "vote", "duty",
			"psychology", "intelligent", "conscious", "cognitive", "sensitive", "accurate", "strict", "severe",
			"actual", "visual", "FALSE", "illegal", "violent", "military", "civil", "typical", "universal", "constant",
			"fundamental", "primary", "rare", "convenient", "enormous", "concentrate", "investigate", "adjust",
			"arrange", "alter", "confirm", "absorb", "expose", "transfer", "abandon", "injure", "recover", "praise",
			"favor", "celebrate", "guarantee", "ensure", "award", "grant", "permit", "disappoint", "embarrass",
			"bother", "upset", "inform", "warn", "command", "imply", "pretend", "interpret", "react", "interact",
			"differ", "breathe", "stare", "breed", "melt", "invest", "manufacture", "construct", "wisdom", "insight",
			"discipline", "habitat", "territory", "colony", "district", "shelter", "landscape", "inhabitant",
			"depression", "nerve", "wound", "symptom", "therapy", "welfare", "incident", "witness", "glance", "ray",
			"ingredient", "agent", "fee", "sacrifice", "burden", "layer", "row", "instruction", "editor", "stuff",
			"mission", "procedure", "immigration", "hybrid", "opponent", "outcome", "equality", "reputation", "capable",
			"proper", "sufficient", "reasonable", "linguistic", "verbal", "bilingual", "contemporary", "conventional",
			"overall", "widespread", "domestic", "distant", "nuclear", "thick", "contrary", "virtual", "aggressive",
			"evil", "elementary", "annual", "immediate", "admire", "approve", "devote", "pursue", "dominate", "possess",
			"occupy", "secure", "capture", "lend", "rent", "persuade", "urge", "stimulate", "annoy", "scare", "crash",
			"collapse", "remark", "illustrate", "protest", "declare", "isolate", "accompany", "surround", "endanger",
			"exhaust", "disturb", "puzzle", "quit", "cope", "enhance", "ease", "apologize", "acknowledge", "resemble",
			"swallow", "distribute", "export", "launch", "justice", "courage", "passion", "bond", "companion", "mood",
			"prejudice", "discrimination", "priority", "globe", "hemisphere", "boundary", "asteroid", "gravity",
			"component", "liquid", "orbit", "trace", "treasure", "logic", "council", "profession", "secretary", "jury",
			"physician", "surgeon", "guard", "license", "grocery", "litter", "drought", "blaze", "trap", "fate",
			"luxury", "exception", "sum", "conservation", "democratic", "numerous", "minor", "superior", "principal",
			"crucial", "vital", "rational", "anxious", "curious", "rude", "remote", "tropical", "marine",
			"extraordinary", "odd", "biological", "racial", "initial", "distinct", "pure", "exact", "sustain", "defend",
			"foster", "pile", "attach", "pour", "load", "stretch", "convey", "derive", "tap", "calculate", "suspect",
			"detect", "attribute", "evaluate", "accuse", "sue", "retire", "shrink", "bow", "peer", "delight", "relieve",
			"discourage", "frustrate", "neglect", "resist", "restrict", "eliminate", "beat", "defeat", "punish",
			"prohibit", "deserve", "pose", "fold", "monitor", "specialize", "accomplish", "faith", "ambition",
			"enthusiasm", "honor", "discount", "fare", "frame", "mode", "architecture", "sequence", "usage", "abuse",
			"pesticide", "pollen", "prefecture", "geography", "administration", "candidate", "rubbish", "bias", "vice",
			"debt", "prospect", "expedition", "session", "semester", "reef", "mineral", "sibling", "proverb",
			"instinct", "minimum", "millennium", "donor", "herd", "league", "cooperation", "fairy", "precise",
			"intense", "solid", "permanent", "brief", "flexible", "informal", "temporary", "frequent", "visible",
			"external", "internal", "plain", "modest", "equivalent", "incredible", "guilty", "raw", "manual",
			"literary", "artificial", "sophisticated", "polish", "embrace", "compose", "imitate", "yield", "exhibit",
			"impress", "overwhelm", "interrupt", "endure", "confront", "consult", "bump", "dispute", "negotiate",
			"justify", "resolve", "reverse", "convert", "impose", "govern", "esteem", "assist", "rescue", "entertain",
			"ruin", "bury", "owe", "chew", "bend", "quote", "classify", "seal", "arrest", "substitute", "retain",
			"restore", "float", "leap", "blossom", "merit", "faculty", "charm", "nutrition", "beverage", "recipe",
			"molecule", "ecology", "ethics", "mankind", "nationality", "pension", "scheme", "haven", "formation",
			"skeleton", "core", "stem", "span", "limitation", "obstacle", "province", "galaxy", "sensation", "sympathy",
			"pity", "tragedy", "divorce", "theft", "panic", "retreat", "jail", "blade", "stroke", "clue", "queue",
			"enterprise", "fortune", "stable", "steady", "mature", "eager", "reluctant", "humorous", "fluent", "prime",
			"precious", "artistic", "ethnic", "primitive", "federal", "royal", "mutual", "apparent", "casual", "slight",
			"mere", "spare", "abstract", "ultimate", "venture", "chase", "migrate", "flee", "swing", "hesitate",
			"postpone", "withdraw", "grip", "grab", "grasp", "gaze", "scan", "forecast", "register", "advocate",
			"trigger", "cultivate", "qualify", "interfere", "clog", "distract", "forbid", "deceive", "overlook",
			"dismiss", "spoil", "yawn", "greet", "nod", "obey", "undergo", "rear", "heal", "cite", "modify",
			"exaggerate", "burst", "thrill", "exceed", "privilege", "liberty", "prosperity", "heritage", "congress",
			"parliament", "infrastructure", "dimension", "portion", "supplement", "appetite", "temper", "fancy",
			"illusion", "fatigue", "stress", "hazard", "infection", "famine", "chaos", "distress", "shame", "cattle",
			"predator", "wilderness", "shade", "monk", "priest", "funeral", "transition", "circulation", "adolescent",
			"equation", "patent", "metaphor", "narrative", "consent", "dignity", "relevant", "adequate", "genuine",
			"prompt", "intimate", "alert", "conservative", "indifferent", "alien", "random", "subtle", "moderate",
			"multiple", "polar", "arctic", "acid", "cosmetic", "extinct", "spiritual", "meaningful", "mechanical",
			"dynamic", "boost", "reinforce", "accumulate", "nurture", "accustom", "correspond", "assign", "regulate",
			"violate", "irritate", "insult", "diminish", "exclude", "rob", "deprive", "deposit", "twist", "blend",
			"mount", "pitch", "cast", "dump", "anticipate", "assess", "pronounce", "spell", "portray", "astonish",
			"emit", "cough", "wander", "drift", "cease", "underlie", "constitute", "resort", "decorate", "reform",
			"conquer", "persist", "incentive", "intuition", "impulse", "fantasy", "destiny", "virtue", "compliment",
			"anniversary", "hive", "nursery", "dormitory", "gallery", "mill", "output", "joint", "phase", "particle",
			"column", "margin", "crack", "mess", "spectator", "prey", "irrigation", "fluid", "prairie", "estate",
			"plot", "realm", "deadline", "poll", "census", "controversy", "combat", "consensus", "treaty", "remedy",
			"triumph", "competent", "brilliant", "sensible", "generous", "brave", "optimistic", "passive", "harsh",
			"ugly", "sensory", "oral", "awkward", "neutral", "vague", "urgent", "inevitable", "concrete", "abundant",
			"sacred", "prominent", "dense", "profound", "tackle", "dedicate", "dare", "accelerate", "transmit",
			"strain", "tempt", "amuse", "disgust", "cheat", "confine", "conceal", "forgive", "discard", "convict",
			"commute", "whisper", "fade", "starve", "vanish", "drain", "dip", "crush", "explode", "terrify", "exploit",
			"elect", "equip", "fulfill", "log", "inherit", "submit", "renew", "reproduce", "flourish", "thrive",
			"spill", "scatter", "sprawl", "prevail", "intellect", "courtesy", "posture", "sociology", "motive", "cue",
			"utility", "chore", "cereal", "fiber", "intake", "scent", "flavor", "mixture", "ratio", "counterpart",
			"patch", "flock", "pedestrian", "librarian", "draft", "formula", "commodity", "asset", "currency", "tide",
			"abortion", "toll", "penalty", "deforestation", "microbe", "outbreak", "epidemic", "syndrome", "outlet",
			"perfume", "reception", "recipient", "keen", "decent", "mild", "humble", "noble", "selfish", "cruel",
			"ridiculous", "deaf", "grateful", "elaborate", "rough", "bitter", "radical", "collective", "exotic",
			"steep", "shallow", "parallel", "probable", "absolute", "aesthetic", "proceed", "bloom", "assert", "bet",
			"boast", "beg", "compromise", "inquire", "yell", "bully", "descend", "crawl", "lean", "spin", "drown",
			"split", "revive", "sigh", "refrain", "sweep", "knit", "cram", "digest", "suppress", "offend", "compensate",
			"compound", "comprise", "transplant", "uncover", "extract", "recruit", "entitle", "appoint", "install",
			"enforce", "implement", "manipulate", "refine", "attain", "quest", "outlook", "premise", "unity", "fabric",
			"thread", "craftsman", "sculpture", "sphere", "curve", "profile", "fingerprint", "criterion", "altitude",
			"tuition", "stake", "acquaintance", "discourse", "gratitude", "worship", "caution", "horror", "decay",
			"defect", "troop", "grave", "ranch", "republic", "county", "cottage", "commerce", "recession", "despair",
			"spray", "compassion", "offspring", "cortex", "fame", "worthwhile", "valid", "thorough", "tremendous",
			"empirical", "secondary", "subsequent", "innate", "interior", "bare", "innocent", "delicate", "ambiguous",
			"fragile", "awful", "inferior", "ashamed", "medieval", "stern", "tense", "imperial", "magnificent",
			"integrate", "incorporate", "utilize", "revise", "prolong", "lessen", "stir", "drag", "scrub", "strip",
			"squeeze", "shed", "plug", "distort", "disrupt", "devastate", "worsen", "abolish", "regain", "exert",
			"precede", "lag", "converse", "utter", "outline", "conform", "designate", "assure", "reassure", "console",
			"induce", "oblige", "compel", "provoke", "bathe", "bleed", "cruise", "soar", "symbolize", "comprehend",
			"protocol", "domain", "index", "transaction", "fragment", "fraction", "bug", "germ", "diagnosis",
			"obsession", "nightmare", "paradox", "irony", "sorrow", "maximum", "excess", "frontier", "refuge", "timber",
			"slavery", "hierarchy", "bureau", "supervisor", "spouse", "rebel", "pastime", "feast", "basin", "sewage",
			"scenery", "tomb", "landmark", "monument", "flesh", "garment", "glimpse", "glow", "grace", "sincere",
			"bold", "tame", "vulnerable", "naked", "immune", "chronic", "gradual", "scarce", "toxic", "accidental",
			"irrelevant", "trivial", "indispensable", "indigenous", "prehistoric", "holy", "retail", "metropolitan",
			"straightforward", "vivid", "outstanding", "enrich", "undertake", "accommodate", "assemble", "embody",
			"weave", "retrieve", "clap", "scratch", "erase", "sew", "cling", "resign", "startle", "evoke", "clarify",
			"confess", "pray", "tolerate", "envy", "revenge", "depart", "overtake", "invade", "penetrate", "enclose",
			"leak", "flush", "sparkle", "erupt", "dye", "halt", "suspend", "surpass", "steer", "navigate", "contradict",
			"contend", "dissolve", "strive", "legacy", "rumor", "verse", "manuscript", "script", "prose", "headline",
			"diameter", "vacuum", "flame", "moisture", "erosion", "peninsula", "suicide", "sin", "taboo", "rage",
			"greed", "boredom", "misery", "plague", "orphan", "liver", "trail", "aisle", "laundry", "merchandise",
			"bargain", "revenue", "deficit", "amateur", "undergraduate", "ambassador", "warrior", "warfare", "botany",
			"anthropology", "ideology", "voluntary", "spontaneous", "deliberate", "conspicuous", "transparent",
			"superficial", "hollow", "peculiar", "partial", "neat", "dim", "alternate", "commonplace", "jealous",
			"hostile", "ripe", "pregnant", "fertile", "fierce", "drastic", "immense", "supreme", "excel", "swell",
			"bounce", "roam", "stray", "emigrate", "mutter", "murmur", "chuckle", "choke", "frown", "roar", "shiver",
			"tremble", "shave", "misunderstand", "soothe", "lure", "mock", "tease", "despise", "disregard", "betray",
			"aspire", "seize", "fetch", "rub", "flap", "plunge", "insert", "dispose", "withstand", "hinder", "resume",
			"unify", "staple", "soybean", "bud", "vegetation", "limb", "wrinkle", "sentiment", "grief", "curse",
			"torture", "mercy", "coward", "predecessor", "psychiatrist", "thesis", "mutation", "diabetes", "bullet",
			"cluster", "shield", "gear", "vessel", "tactics", "breakdown", "reunion", "knot", "probe", "radiation",
			"tablet", "vapor", "thermometer", "signature", "triangle", "geometry", "feat", "applause", "glory",
			"diligent", "earnest", "loyal", "stubborn", "rigid", "stiff", "timid", "idle", "dumb", "obese", "disabled",
			"clumsy", "punctual", "absurd", "uneasy", "nasty", "naughty", "tidy", "decisive", "upright", "vertical",
			"gloomy", "obscure", "antique", "sole", "sheer", "marvelous", "splendid", "cherish", "nourish", "hatch",
			"enlarge", "furnish", "indulge", "surrender", "kneel", "stumble", "wither", "creep", "ache", "await",
			"foresee", "illuminate", "dread", "depict", "signify", "swear", "dictate", "recite", "enroll", "execute",
			"fake", "disguise", "stain", "bind", "slap", "omit", "grind", "undermine", "bankrupt", "extinguish", "mend",
			"congratulate", "certificate", "encyclopedia", "biography", "masterpiece", "rhyme", "means", "mold",
			"scope", "bulk", "trifle", "pill", "dose", "vein", "odor", "pilgrim", "deed", "carriage", "mischief",
			"slaughter", "haste", "thirst", "monarchy", "reign", "heir", "pardon", "legislation", "cabinet", "ward",
			"surplus", "arithmetic", "mercury", "monopoly", "friction", "collision", "fusion", "breakthrough",
			"spectacle", "eminent", "notable", "notorious", "compulsory", "liable", "inclined", "static", "infinite",
			"eternal", "acute", "abrupt", "swift", "faint", "tender", "humid", "damp", "rotten", "sour", "sore",
			"savage", "crude", "approximate", "intermediate", "vocational", "masculine", "feminine", "superfluous",
			"utmost", "contemplate", "ponder", "meditate", "conceive", "speculate", "presume", "proclaim", "disclose",
			"pledge", "exclaim", "subscribe", "mourn", "resent", "lament", "pant", "suck", "soak", "render", "rotate",
			"pierce", "carve", "divert", "expel", "assault", "intrude", "addict", "coincide", "ascend", "surge",
			"evaporate", "expire", "ferment", "merge", "erect", "bless", "prestige", "aristocracy", "statesman",
			"senator", "creed", "vigor", "dismay", "melancholy", "agony", "anguish", "conscience", "contempt", "scorn",
			"apathy", "textile", "symmetry", "verge", "cavity", "bribe", "riot", "exile", "archaeology", "specimen",
			"ornament", "apparatus", "flaw", "eclipse", "astronomy", "aviation", "velocity", "congestion",
			"questionnaire", "parasite", "personnel", "advent", "token", "premium", "discreet", "wary", "grim",
			"solemn", "skeptical", "dubious", "vain", "reckless", "ruthless", "eloquent", "furious", "weary",
			"pessimistic", "cynical", "wicked", "singular", "weird", "literal", "explicit", "implicit", "slender",
			"gross", "ultraviolet", "spatial", "vacant", "spacious", "ample", "affluent", "infer", "discern", "allege",
			"ascribe", "prescribe", "comply", "abide", "plead", "preach", "intrigue", "reconcile", "intervene",
			"restrain", "humiliate", "reproach", "condemn", "defy", "revolt", "impair", "inflict", "degrade",
			"deteriorate", "corrupt", "contaminate", "oppress", "thrust", "embark", "inspect", "summon", "testify",
			"persecute", "coerce", "unleash", "emancipate", "endow", "scrutiny", "analogy", "preoccupation",
			"retrospect", "conceit", "fallacy", "hypocrisy", "nuisance", "delinquency", "hostage", "lawsuit",
			"attorney", "warrant", "testimony", "verdict", "sanction", "superstition", "folklore", "anecdote",
			"rhetoric", "stall", "segment", "synthesis", "cohesion", "heredity", "catastrophe", "plight", "solitude",
			"ordeal", "tyranny", "censorship", "hygiene", "doctrine", "diplomacy", "entity", "sovereign", "authentic",
			"legitimate", "intelligible", "inherent", "ingenious", "intricate", "homogeneous", "monotonous",
			"incessant", "perpetual", "imminent", "plausible", "arbitrary", "preliminary", "deficient", "subordinate",
			"feudal", "obsolete", "mortal", "monetary", "extravagant", "dizzy", "juvenile", "anonymous", "compatible",
			"ubiquitous", "divine", "sober", "zealous"
	};

	// 意味
	public static String[] meanings = { "", "を向上させる；よくなる", "を（...と）関連づける（to）；（...に）関連する（to）", "を供給する（≒supply）",
			"を見なす；について考える", "を含む（⇔exclude を除外する）", "（受身形で）（...を）心配する（about）；（受身形で）（...に）関係する（with）；に関連する", "を関与させる；を伴う",
			"を生産する；を取り出す", "を許す；を与える；（...を）考慮に入れる（for）", "を要求する；を必要とする", "...のように見える；現れる", "傾向がある；を世話する",
			"意見が一致する；同意する", "について述べる", "を（...に）加える（to）", "頼る；...次第である", "を励ます（⇔discourage にやる気をなくさせる）", "存在する；生存する",
			"を減らす；を（...に）変える（to）", "適応する；を（...に）適合 させる（to）", "を比較する；を（...に）例える（to）", "増加する（⇔decrease 減少する）；を増やす",
			"を提案する；を暗示する", "（費用）がかかる；を犠牲にさせる", "を共有する；を分担する", "かなと思う；（...に）驚嘆する（at）", "と主張する（≒claim，maintain）；議論する",
			"に気づく；を実現する", "を管理する；を制御する", "に影響を及ぼす（≒influence）；を感動させる", "とわかる；を見つける", "に気づく", "を避ける", "に強いる；を強要する",
			"を提供す る，申し出る", "を要求する", "と主張する；を自分のものだと主張する", "（deal withで）を処理する", "を保存する； を蓄える", "を完成させる",
			"価値；価格；評価；（～s）価値観", "利益，恩恵；給付金", "機会（≒chance）", "質（ ⇔quantity 量）；特質", "著者；張本人", "科学技術；応用技術",
			"環境（≒surroundings）", "（...についての）見解（on / about）；眺め", "状況；（人の置かれた）立場", "（...に対する）影響，効果（on / upon）；結果",
			"（...に対する ）影響（力）（on）", "（専門）用語；（～s）条件；（～s）間柄；学期", "技能；熟練", "理論，学説；原理；推測", "問題（点）；発行（物）；発表", "話題；学科；主題；被験者",
			"記事；条項；品物", "主張；声明；明細書", "（...を使っ ての）実験（with）", "数字；姿；人物；図（表）", "証拠", "産業；勤勉（≒diligence）", "経済；節約",
			"医薬（≒medication）；医学", "問題；（～s）事態；（the ～）困難；物質", "材料；資料；生地", "（生物の）種；種類", "（社会の）慣習；実践；練習", "焦点；関心の的",
			"記憶（力）；（...の）思い出（of）", "権利；右；正しいこと", "一致；合 意，協定", "考え；思考", "（...に対する）興味（in）；利子；利害", "説明；勘定；口座",
			"原因（⇔effect 結果）；理由；大義", "音；響き，印象", "個人", "確信して；確かな；ある；一定の", "可能な；可能性のある", "ありそうな（⇔unlikely ありそうもない）",
			"手に入る；利用できる；手が空いている", "社会的な；社交の", "公の（⇔private 私的な） ；公開の", "身体の；物質的な；物理学の", "科学的な；（自然）科学の", "普通の；共通の；一般の",
			"全般的な；一般的な", "特定の；特別の；（...について）やかましい（about）", "似ている；同様の", "さまざまな；いくつかの", "出生地の；原産の；生得の", "忍耐強い；勤勉な", "最近の",
			"...さえ；（比較級の前で）いっそう", "（文頭で）それでも；（ 否定文で）まだ；（疑問文で）もう", "かなり；むしろ；それどころか", "その代わりに；そうではなくて",
			"（...と）同時 に（with）；一斉に", "それぞれ；どれもこれも", "に異議を唱える；（人）に挑む", "を決定する；を正確に知る", "をどうにか成し遂げる；を管理する", "を維持する；と主張する",
			"言及する；関連する；参照する", "に近づく；に取り組む", "進歩する；進む；を進める", "を表現する", "を広める；広がる", "起こる；心に浮かぶ；現れる", "に気づく；を観察する；を遵守する",
			"を識別できる；を認める", "と思う；と仮定する", "を見なす；を見る；を評価する", "を扱う；を治療する", "捜す；を捜索する；を詳しく調べる", "を証明する；わかる，判明する",
			"を設立する；を確立する", "に言及する；と言う", "を表す；を代表する", "の方を好む", "申し込む；（...に）適用される（to / in）；を（...に）適用［応用］ する（to）",
			"を追い求める；（助けなど）を要請する", "を出版する；を公表する", "を行う；を演じる，演奏する", "を獲得する；（を）増す",
			"（に）適合する；を（...に）はめ込む（in / into）；を（...に）合わせる（to）", "を含む；の収 容能力がある；を抑える", "を供給する",
			"を準備する；を調理する；（...のために）準備をする（for）", "に耐える（≒stand，endure）；を負う；を産む；を運ぶ", "を妨げる；を防ぐ", "（...に）反対する（to）",
			"衰退する；減少する；を断る", "に取って代わる；を取り替える", "をつなぐ；を（...と）関連づける（with）", "に出席する；（の）世話をする；（...に）精を出す（to）",
			"生き延びる；を切り抜けて（生き）残る；より長生きする", "を尊敬する；を尊重する", "を浪費する", "利点（⇔disadvantage 不利な点）；優勢；有利，得",
			"（通例 ～s）資源；（通例 ～s）資金；才覚", "（情報伝達の） 媒体；手段", "方法；体系；秩序", "（...に対する）考え方（toward / to）；態度", "構造；体系；構造物", "機能；関数",
			"特徴；（～s）顔つき；特集記事［番組］", "（物事の）側面；観点；様相", "内容；中身；コンテンツ", "（～s）詳細（な情報），細部", "範囲；射程距離；並び", "地域；領域；部位",
			"貿易；商売，取引", "習慣，癖", "細胞；小個室；電池", "燃料；勢いを増加させるもの", "請求書；【英】勘定書（≒【米】check）；法案", "料金；世話；管理；告発",
			" （...に対する）罰金（for）", "温度；体温；熱", "10年間", "感情，情動；感動", "説明；解釈；理由", "解決（策）；溶液", "程度；度；学位；等級", "接近，利用（の機会）",
			"（...との）対照（with / to）", "地位；状態", "表面；外見", "争い；論争；不一致", "（集合的に）聴衆；視聴者", "粘土", "時代；画期的な出来事", "利益；収益（率）；得",
			"収入", "先祖（⇔descendant 子孫）；先駆者；原型", "（しばしば ～s）作物；収穫高", "重要な；意義深い", "必要 な（≒essential）", "（...に）適切な（for / to）",
			"正しい；適切な", "の価値がある；（～する）に値する（doing）", "積極的な；肯定的な；明確な；確信して", "柔軟な；プラスチックの，ビニールの", "政治（上）の", "公式の；公用の； 役所の",
			"私的な（⇔public 公の）；民営の", "古代の；昔からの", "（支払）期日で；予定された；しかるべき", "複雑 な；複合（体）の", "可動［移動］式の；流動性のある",
			"空白の；無表情な；がらんとした", "男性の（⇔female 女性の） ；男らしい", "それゆえに", "したがって；このように；次のように", "結局（は）", "さもなければ；その他の点では；違った風に",
			"...にもかかわらず（≒in spite of）", "両方とも；両方の", "（...に）成功する（in）；（...を）継承する（to）", "を特定する；を（...と）同一視する（with）",
			"を反映する；（を）反射する；（を）熟考する", "を当然のことと 思う；を手に入れる；を引き受ける", "と推定する；を見積もる；を評価する", "を定義する；を規定する", "を指し示す；を述べる",
			"を明らかにする；を見せる", "を試みる，企てる", "反応する；答える", "を結び付けて考える；（...と）交際 する（with）", "を調べる；を診察する；を尋問する",
			"（問題など）を扱う；に演説する；（手紙など）を（...あてに）出す （to）", "を信頼する；を託する", "を疑う；（...では）ないと思う（that節）", "を無視する", "を拒む；を断る",
			" （と）不平［苦情］を言う；訴える", "減少する（⇔increase 増加する）；を減らす", "さまざまである", "現れる；明らか になる；台頭する", "と合う；に匹敵する",
			"を動けなくさせる；（...に）くっつく（to / on）", "を隠す（≒conceal）； 隠れる", "を引きつける", "を促進する；（受身形で）昇進する", "を満足させる；を満たす",
			"を稼ぐ；を得る；をもたらす", "を保持する；を守る；を保存する", "（人）にとって（～するのを）可能にする（to do）", "を破壊する；（人）を破 滅させる", "を引き裂く；裂ける",
			"苦しむ；患う；（苦痛など）を経験する", "を調査する；を概観する", "を分ける；分かれる", "を実施する", "（...を）卒業する（from）", "寄与［貢献］する；（を）寄付する；（を）寄稿する",
			"を強く 望む", "くつろぐ；緩む；をくつろがせる；を緩める", "（到達）目標；的", "目的", "主義，信条；原則，原理", "規範；標準", "戦略", "跡；軌道；【米】（鉄道の）番線；走路",
			"進歩；前進", "個性，性格", "（しばしば ～s）特徴", "方法；物腰；（～s）作法", "装置，機器；方策", "起源；源", "遺伝子", "大気；雰囲気", "傾向；流行", "現象",
			"状況，背景；文脈", "（通例 ～s）状況，事情；境遇", "苦痛；苦悩；（～s）骨折り", "闘い；懸命の努力", "汚染", "脅威；兆し，恐れ；脅迫", "災害；惨事", "（通例 ～s）結果；重大性",
			"革命；回転；（天体の）公転（⇔rotation 自転 ）", "大部分；多数派（⇔minority 少数派）", "かたまり；大量；一般大衆", "在庫品；蓄え；株", "富；資源；富裕（状 態）",
			"文学；文献；印刷物", "（the ～ties）（関係）当局；権威；権限", "機関；協会；施設；制度", "（社会的な）慣習；（～s）税関；（～s）関税",
			"光景；（the ～s）名所；目にすること；視野；視力", "（感情などの）表れ；展示；誇示", "（職場の）同僚（≒coworker）", "居住者", "乗り物，車；伝達手段，媒体",
			"（...に）必要不可欠な（to）；本質的な", "気づいて", "精神の；知能の", "学問の；大学の", "並の；普通の；常勤の", "精通している；よく知られている", "目新しい，斬新な",
			"特定の；明確な，具体的な；（...に）特有の（to）", "化学の，化学的な", "財政（上）の；財界の", "活動的な；効力のある；積極的な",
			"否定の（⇔affirmative 肯定の）；消極的な（⇔positive 積極的な）；負の", "直接の（⇔indirect 間接の）；率直な", "明らかな（≒clear）", "現在の；現代の；通用している",
			"都市の；都会的な（⇔rural 田舎の）", "さらに", "同様に（≒in the same way）", "（文中，文末で）けれど", "それにもかかわらず（≒nonetheless）", "それによって",
			"それゆえに（≒therefore）", "を正当に評価する；を鑑賞する；を感謝する", "（を）認める；に （...への）入場［入学など］を認める（to / into）", "を予言［予測］する",
			"を得る；を習得する", "を採用する；（態度など）をとる；を養子にする", "を購入する", "を持つ［する］余裕がある；を与える", "を消費する；を食べる，飲む", "を取り除く；を解雇する",
			"に適する；に似合う；を適合させる", "（を）拡大する；（を）詳説する", "を伸ばす，延ばす；伸びる；及ぶ", "（を）調査する；（を）探検する", "（を）判断する；に判決を下す",
			"を論証［証明］する；デモをする", "（を）強く主張する", "訴える；抗議する；上訴する", "を納得［確信］させる", "を解決する；（に）移り住む", "を援助する，助ける",
			"を教育する；に教える；（能力など）を養う", "を従事させる；を（...として）雇う（as）；（...に）従事する（in / with）", "を結び付ける；（...と）結び付く（with）",
			"を組織する；を準備する", "を操作する；機能する；手術する", "を思い出す；を呼び戻す", "頼る（≒depend）", "をびっくりさせる", "を混同する；を当惑させる", "を責める；の責任を負わせる",
			"を批判する；を批評する", "振る舞う；作用する", "に遭遇する；に（思いがけず）出会う", "を選ぶ，精選する", "流れる；（...から）生じる（from）", "（徐々に）発展する；進化する",
			"凍る；態度を硬くする；を 凍らせる", "を放出する；を解放する；を発表する", "の位置を探し当てる；（受身形で）位置する", "を宣伝する；（...を 求める）広告を出す（for）", "想像（力）",
			"観点；大局観；遠近法", "自信；信頼；秘密", "業績；達成，成就", "報 酬；報い", "（大）企業；法人", "資本；首都；大文字（＝capital letter）",
			"顧客（≒customer）；（弁護士などの）依頼人", "危機", "害", "犠牲（者），被害者", "選択（の自由）；選択肢", "運動；軍事行動", "裁判所，法廷；裁判；宮廷；中庭",
			"規範；暗号，符号；法典", "犯罪者，犯人", "農業；農学，畜産", "宗教；信条；信仰（心）", "哲学；原理；人生観", "会議；協議", "（公）文書；記録，資料", "統計；統計学", "分析（結果）",
			"仮説；憶測", "概念，観念；見解；意向", "固定観念；決まり文句", "（書物などの）論評；再調査；【米】復習", "語彙", "臓器；組織", "（社会的・文化的）性別", "化石；時代遅れの人［物］",
			"氷河", "実験室，研究室", "ウイルス；（感染症の）病原体", "場合，時；行事；機会", "大臣；（プロテスタント系の）聖職者", "存在；出席；面前", "物質；実質；趣旨",
			"創造的な，独創的な；創造力のある", "潜在的な；可能性を秘めた", "（...から）独立した（of / from）", "いとわない", "効率的な；有能な", "理想的な；観念的な",
			"遺伝（子）の；発生の", "全体の，全部の（≒whole）；完全な", "相対的な（⇔absolute 絶対的な）；比較上の；（...と）関連した（to）", "極端な；極度の，過激な", "広大な；莫大な",
			"とても小さな；わずか な", "人の住まない；砂漠の（ような）", "田舎の（⇔urban 都会の）", "以前の，前の", "法律の；合法の（⇔illegal 違法の）",
			"近ごろは（≒these days，today）", "めったに...ない（≒rarely）", "（2つの事柄を対比して）一方；その間", "（the ～）（二者のうちの）後者（⇔the former 前者）",
			"（A versus Bで）A対B；AかBか", "すべて（のもの）；全く", "を知覚する", "を予期する；を期待する", "を意図する", "を要請する；に（～するように）頼む（to do）",
			"に思い出 させる", "（人）を触発する；を喚起する", "を魅了する", "を強調する；を重視する", "を勧める", "を提案する；をもくろむ；結婚を申し込む", "を区別する", "を複雑にする",
			"を変える；変わる", "（功績など）を（...に）帰する（to） ；を信じる", "（判断など）を保留する；を予約する；を取っておく", "に反対する；を対抗［対比］させる", "を否定する；を拒む",
			"を拒否する", "を（法的に）禁止する；を締め出す", "（人）を怖がらせる", "参加する", "競う；匹敵する", "を克服する", "生じる", "を生み出す", "を得る", "を雇う；を使う",
			"を輸入する（⇔export を輸出する）；を取 り入れる", "を処理する；を論じる；を商う", "を修理する（≒fix）；を修復する", "を治す；を除去する；（病気が）治る", "を輸送する",
			"を配達する；（演説・講義）をする；子を産む", "急いで行く；性急に行動する；をせき立てる", "（commit oneself または受身形で）深くかかわる；（罪など）を犯す", "をひどく嫌う；を残念に思う",
			"を後悔する", "（...か ら）成る（of）；（...に）ある（in）", "を翻訳する；を（...に）変える（into）", "と結論づける；を締めくくる；を締結する", "快適さ；慰め",
			"施設，設備；機能；才能", "特性（≒feature）", "人類；人間性；人情", "部族", "（通例 the ～）（集合的に）エリート", "弁護士", "部類；区分", "（本・製品などの）版；解釈",
			"多様性；相違点", "割合；部分；釣り合い", "器具；楽器（＝musical instrument）", "革新；新機軸", "兵器，武器", "方言",
			"（...に対する）障 壁（against / to）；防壁；境界線", "作り話；神話", "儀式；（日常の）習慣的行為", "決まり切った仕事；いつもの手順", "緊急（事態）", "不安；警報",
			"収穫（物）；漁獲高", "穀物；粒；きめ", "量（⇔quality 質）", "予算；経費", "（～s）経費；費用；犠牲", "保険；保険料；保険金", "貸付金，融資；貸し付け", "契約（書）；協定",
			"哺乳動物", "乳児；幼児", "たんぱく質", "（生物の）組織；ティッシュペーパー", "（通例 one's ～）責任；欠点；誤り", "地域；近所", "投票；投票結果；（the ～）選挙権",
			"義務；職務；関税", "心理学", "聡明な；知能を有する", "意識して，気づいて（≒aware）", "認知の", "敏感な；神経質な；微妙な", "正確な；精密な", "厳格な；（規則などが）厳しい",
			"（ 人・規律などが）厳しい；猛烈な", "実際の", "視覚の；目に見える", "誤った；うその；偽の", "違法の，不法の（⇔legal 合法の）", "暴力的な；（人・気質が）激しい", "軍の",
			"市民の；民間の；民事の（⇔criminal 刑事の）", "典型的な ；（...に）特有の（of）", "普遍的な；宇宙の；万能の", "絶え間ない；一定の", "基本的な；必須の",
			"最も重要な；第 一の；初等（教育）の", "珍しい，希少な", "便利な，都合のいい", "巨大な，莫大な", "（を）集中する", "を調査する；を究明する；（...を）調査する（into）",
			"を調整する；を適合させる；順応する", "の段取りをつける；を手配する；を配 置する", "を変える；変わる（≒change）", "を確認する", "を吸収する；を併合する",
			"をさらす；を暴露する；を露出する", "を移す；を伝える；移る；乗り換える", "を捨てる；を放棄する", "を傷つける；を損なう（≒hurt）", "回復する；を取り戻す",
			"を（...のことで）賞賛する（for）；賛美する", "に賛成する；を好む；をひいきする", "を祝う；を挙行する", "を保証する", "を確実にする（≒make sure）；を守る",
			"を授与する；を裁定する", "を与える；を認める", "を許 可する（≒allow）", "を失望させる；（希望など）をくじく", "に恥ずかしい思いをさせる",
			"を悩ます；（...を）気にかける（about / with）", "を動揺させる；をだめにする", "に知らせる；情報を提供する", "（人）に（...について）警告する （of / against）",
			"と命じる；を指揮する；を支配する；（景色）を見渡せる；を操る", "を暗に意味する；を必然的に伴う", "のふりをする", "を解釈する；（を）通訳する", "反応する；化学反応を起こす",
			"影響し合う；相互に作用する", "異なる", "呼吸する；を吸う", "（を）じっと見る", "を飼育する，繁殖させる；繁殖する；生じる", "溶ける；なごむ；を溶かす",
			"（を）投資する；に（...を）与える（with）", "を製造する；をでっち上げる", "を建設する；を構成する", "知 恵；学識", "洞察力，見識", "規律，しつけ；訓練；懲戒；学問分野",
			"生息地；（人の）居住地", "領土；（活動などの）領域", "植民地；居留地；（動植物の）コロニー", "地区；行政区", "避難（所），保護", "風景；領域", "住民；生息動物",
			"憂うつ；うつ病；不況；低気圧", "神経；（～s）神経過敏；（～する）度胸（to do）", "（銃弾・刃物などによる）傷；痛手", "症状；兆候（≒sign）", "療法；心理療法", "福祉，幸福",
			"出来事，事件；紛争", "目撃者（≒eyewitness）；証人；証拠，証言", "（...を）ちらっと見ること（at）", "光線", "成分，材料；要素", "仲介者，代理人；薬剤", " 料金；謝礼",
			"犠牲；いけにえ", "負担；（重い）義務；積み荷", "層", "列；（建物が並ぶ）通り", "（通例 ～s）指示；（～s）（製品の）使用書", "編集者", "（漠然と）物；素材；素質",
			"使命；（外交）使節団", "手続き；（一連の）措 置", "（外国からの）移住（⇔emigration （外国への）移住）；入国管理事務所（＝immigration control）",
			"ハイブリッド車；（動植物の）雑種；混成物", "（試合・論争などの）相手；反対者", "結果（≒result）", "平等，対等", "評判", "能力がある；有能な",
			"適切な；正式の；（...に）固有の（to）", "（...に；～するのに）十分な（for ；to do）（⇔insufficient 十分でない）", "合理的な；分別のある；（値段が）手ごろな", "言語の",
			"言葉の；口頭での；逐語的な", "2言語を 使う", "現代の；同時代の；同年輩の", "従来の；月並みな", "全体的な", "広範囲にわたる；広く普及した", "家庭の；国内の；（動物が）飼いならされた",
			"遠い；隔たった", "核の，原子力の", "厚い（⇔thin 薄い）；太い；濃い", "（...と）反対の（to）", "仮想の；事実上の", "攻撃的な；意欲的な", "邪悪な；有害な", "初級の；基本的な",
			"1年間の； 年1回の，例年の", "即座の；当面の；すぐそばの；直接の", "に（...のことで）感嘆する（for）", "賛成する；を承認する", "をささげる", "を追求する；に従事する",
			"を支配する；（...より）優勢である（over）", "を所有している；の心をとらえる", "（空間・時間）を占める；を占領する", "を確保する；を守る", "を捕らえる；を引きつける",
			"を貸す（⇔borrow を借りる）；（人）に（物）を与える", "を賃借りする；を賃貸しする", "を説得する；に確信させる", "に促す；を強く 主張する；を追い立てる", "を刺激する",
			"を悩ます；（受身形で）腹が立つ", "をおびえさせる；を脅す", "衝突する，墜落する；をぶつけて壊す", "崩壊する；（人が）倒れる；を折り畳む",
			"と述べる；（...について）意見を述べる（on / upon）", "を説明する；に挿絵を入れる", "抗議する；を主張する", "を宣言する；を申告する", "を孤立させる", "に同行する；に付随する",
			"を取り巻く；にまつわる", "を危険にさらす", "を疲れ果てさせる；を使い尽くす；排気する", "をかき乱す；を邪魔する；を不安にする", "を当惑させる", "をやめる；（場所）を去る", "うまく処理する",
			"（価値など）を高める", "を軽減する；和らぐ；緩む", "（...に；...のことで）謝る（to；for）；弁明する", "を認める（≒admit）；に謝意を表す", "に似ている",
			"（を）飲み込む；をうのみにする；に耐える", "を分配する；（受身形で）分布する", "（を）輸出する（⇔import 輸入する）", "を開始する；を売り出す；を発射する", "公正，正義；司法", "勇気",
			"情熱；熱中；激怒", "絆；債券；束縛；接着剤", "連れ；仲間", "気分；機嫌；雰囲気", "（...に対する）偏見（against）（≒bias）", " （...に対する）差別（against）；区別",
			"優先（事項）", "地球（≒earth）；世界；球", "半球", "境界（線）；（通例 ～ies）限界", "小惑星（≒minor planet）；ヒトデ", "重力，引力；重量；重大さ", "構成要素；部品",
			"液体", "軌道 ；範囲", "痕跡；微量", "宝物；財産", "論理；道理；原理", "（地方）議会；評議会；（公の）会議", "職業；専門職；同業者仲間", "秘書；事務官；【米】長官",
			"陪審（員団）；審査員団", "内科医", "外科医；軍医", "護衛者；監視，警戒", "免許（証）", "（～ies）食料雑貨；食料雑貨店", "ごみ；乱雑な状態", "干ばつ；（慢性的な）不足",
			"炎；強い 輝き", "わな；苦境", "運命；結末；最期", "ぜいたく（品）；（形容詞的に）豪華な", "（...の）例外（to）", "金額 ；合計；要点", "（動植物などの）保護；保存",
			"民主主義の；民主的な", "非常に数の多い", "小さい（⇔major 大きい方の）；重要でない", "よりすぐれた（⇔inferior より劣った）", "主要な；資本金の", "重要な；厳しい",
			"必要不可欠な ；生き生きした；生命にかかわる", "理性的な；合理的な（⇔irrational 不合理な）", "心配して；切望して", "好奇心の強 い；奇妙な",
			"無礼な（⇔polite 礼儀正しい）；粗野な", "（...から）遠く離れた（from）；かけ離れた", "熱帯の", "海の；船舶の", "異常な（⇔ordinary 普通の）；並はずれた",
			"奇妙な（≒strange）；奇数の", "生物学（上）の", "人種の，民族の", "初めの", "明らかに異なる；明瞭な", "純粋な；潔白な；全くの", "正確な；まさにその", "を持続させる；を支える",
			"を防御する；を弁護する", "を促進する；を養育する；を心に抱く", "を積み重ねる；積み重なる", "を付ける；を付与する", "を注ぐ；（を）放出する；激しく降る；押し寄せる", "に積む；に負わせる",
			"を伸ばす；を広げる；伸びる；及ぶ", "を伝える；を運ぶ", "由来する；を引き出す；を推論する", "（を）有効利用する；を引き出す；を軽くたたく", "を計算する；を予測する",
			"ではないかと思う；（人）を疑う", "を感知する；を見つけ出す", "（結果など）を（...に） 帰する（to）", "を評価する；を査定する", "を非難する；を告訴する",
			"を告訴する；（...を求めて）訴訟を起こす（for）", "（...から）引退する，退職する（from）", "縮む；減少する；ひるむ", "おじぎする；屈服する",
			"（...を）じっと見る（at / into）", "を喜ばせる；（...を）大いに喜ぶ（in）", "を和らげる；（受身形で）（～して）安心する（to do）；を 解放する",
			"（人）にやる気をなくさせる；を落胆させる（⇔encourage を励ます）", "を挫折させる；（受身形で）（...に） 不満を抱く（with）", "を怠る；を無視する", "に抵抗する；（否定文で）に耐える",
			"を制限する", "を取り除く", "（を）打つ；を打ち負かす", "を負かす（≒beat）；を失敗させる", "を罰する；に損傷を与える", "を禁止する", "に値する",
			"（問題など）を提起する；ポーズをとる；（...を）装う（as）", "を折り畳む；畳める；（腕など）を組む", "を監視す る；を傍受する",
			"専門とする；【英】（...を）専攻する（in）（≒【米】major）", "を成し遂げる", "（...への）信頼（in）；信仰（心）", "（...への）野望（of / for）；野心",
			"（...への）熱情（for）", "光栄；名誉（⇔dishonor 不名誉） ；敬意", "割引", "（乗り物の）料金", "枠，縁；骨組み；体格", "方式；気分；形態；流行", "建築；建築様式；構造",
			"一連（のもの）；連続", "語法；使用（法）", "濫用；虐待", "殺虫剤；除草剤（≒herbicide）", "花粉", "県，府", "（the ～）地理；地理学", "管理（部）；行政；政府（機関）",
			"（...の）候補（者）（for）；【英】志願者", "【英 】ごみ（≒【米】garbage）；つまらないもの", "偏見；傾向", "悪（⇔virtue 美徳）；欠点", "借金；恩義",
			"見込み；（～s）展望；有望な人", "遠征（隊）", "集まり；（議会の）会期；（開会中の）議会", "学期", "（岩や砂の）礁；暗礁", "鉱物；ミネラル", "きょうだい", "ことわざ（≒saying）",
			"本能；（自然に起こる）衝動；勘", "最小限度（⇔maximum 最大限）", "千年間，千年紀", "寄贈者；臓器［血液］提供者", "（牛などの）群れ；群衆", "（競技）連盟；同盟", " 協力",
			"妖精の（ような）", "正確な（≒exact）；精密な；まさにその", "強烈な；熱烈な", "固体の；頑丈な", "永続 的な（⇔temporary 一時的な）", "短い；簡潔な", "融通の利く，柔軟な",
			"形式ばらない，略式の（⇔formal 正式の）", "一時的な（⇔permanent 永続的な）", "頻繁な", "（目に）見える（⇔invisible 見えない）；明白な",
			"外部の（⇔internal 内部の）；対外的な；表面的な", "内部の（⇔external 外部の）；国内の；内面的な", "明らかな；平易な；率直な", "謙 虚な（≒humble）；適度な；質素な",
			"等しい，相当する", "信じられない；すばらしい", "罪悪感のある；（...について） 有罪の（of）", "生の；未加工の", "体を使う；手の；手動式の",
			"文学の；文語の（⇔colloquial 口語体の）", "人工の （⇔natural 自然の）；不自然な", "洗練された；精巧な", "を磨く；を洗練させる", "を受け入れる；（を）抱擁する；を包含する",
			"を構成する；を創作する；を鎮静する", "をまねる；を模造する", "をもたらす；を産出する；を（...に）譲る（to）；（...に）屈する（to）", "を展示する；（感情など）を表す",
			"を感動させる；に印象を与える", "を圧倒する；を打ちのめす", "を中断させる；（の）邪魔をする", "に耐える（≒put up with）；存続する", "に立ち向かう；（困難などが）に 立ちはだかる",
			"（に）相談する；を参照する", "（bump into で）に偶然出会う；（に）ぶつかる；をぶつける", "に異議を唱える；（を）議論する", "交渉する；を（交渉して）取り決める", "を正当化する",
			"を解決する；を決意する；を議決する", "を逆転させる；を反対にする", "を変える；を交換する", "を課す；を押し付ける", "（を）支配する；（を）統治する", "を尊敬する；を見なす",
			"（を）援助する；を手伝う", "を救う", "を楽しませる；をもてなす", "をだめにする；を破滅させる；滅亡する", "を埋める；を埋葬する；を隠す", "に借りがある；のおかげである", "（を）噛む",
			"を曲げる；を屈服させる；曲がる", "を引用する；を引き合いに出す", "を分類する；を機密扱いにする", "を密閉する；に封をする", "を逮捕する；を止める；（注意）を引く",
			"を代わりに使う；（...の）代理をする（for）", "を保持する；を覚えている", "を回復させる；を修復する", "浮かぶ；漂う；を浮かべる", "跳ぶ；さっと動く；急上昇する",
			"花が咲く（≒bloom）；発 展する", "利点（⇔demerit 欠点）；功績；真価", "能力，機能；学部；教授陣", "魅力；お守り", "栄養（の摂取）", "（水以外の）飲み物，飲料",
			"調理法，レシピ；手順", "分子；微粒子", "生態学；生態系；環境保護", "倫理，道徳", "人類", "国籍；国民；国民性", "年金", "計画（≒plan）；体系；陰謀", "避難所，保護区；港",
			"形成；構成物；隊列", "骨格；骨組み", "核心；芯", "（草木の）茎，幹", "期間；範囲", "制限；（通例 ～s）限界", "（...に対する）障 害（物）（to）",
			"州，県；（the ～s）地方；分野", "星雲，銀河", "感覚；大評判", "同情；（...に対する）共感（with / for）", "哀れみ；残念なこと", "悲劇（的な事件）（⇔comedy 喜劇）",
			"離婚；分離", "窃盗（罪）", "狼狽，パニ ック", "後退，退却；引退", "刑務所，拘置所", "刃；（プロペラなどの）羽根；（草などの）葉", "脳卒中；打つこと；一撃",
			"（...の）手がかり（to）；（パズルの）ヒント", "【英】（順番を待つ）列（≒【米】line）", "企業；事業；進取の 気性", "財産；幸運（≒luck）；運命", "安定した；動じない",
			"着実な；安定した", "成熟した（⇔immature 未熟な）； 熟した", "（...を）熱望して（for）；熱心な", "気が進まない，嫌がる（⇔willing いとわない）",
			"ひょうきんな；ユーモアのある", "流ちょうな", "最も重要な，第一の", "貴重な；高価な（≒valuable）", "芸術的な", "民族の，人種の；民族特有の", "原始的な；未開の",
			"連邦（政府）の", "王の", "相互の；共通の", "明白な；一見...らしい", "何気な い；形式ばらない", "わずかな；取るに足らない", "単なる，ほんの", "余分の；予備の",
			"抽象的な（⇔concrete 具体的 な）", "究極の", "危険を冒して進む；思い切ってする", "（を）追跡する；（を）追求する", "移住する；（鳥などが）渡る", "（から）逃げる",
			"を揺らす，振る；揺れる；一変する", "躊躇する", "を延期する（≒put off）", "を引き出す ；を撤回する；撤退する", "を握る；をとらえる", "をつかむ；を横領する；を急いで食べる",
			"を把握する；をしっかり握る", "じっと見る", "を注意深く調べる；をざっと見る", "を予想する；を予報する", "を記録する，登録する；を示す", "を主張する；を擁護する", "を引き起こす",
			"を養う；を栽培する", "（人）に資格を与える；資格がある", "干渉する，介入する；邪魔する", "を詰まらせる；を阻害する；詰まる", "（注意など）をそらす", "を禁じる",
			"をだます（≒take in ）", "を見落とす；を大目に見る；を見渡す", "（意見など）を退ける；を解雇する", "を台無しにする；を甘やかす；だめになる", "あくびをする", "に挨拶する；を迎える",
			"うなずく；うとうとする", "に従う；に服従する", "を経験する；を受ける；に耐える", "（人・動物・植物）を育てる（≒raise, breed）", "を治す；治る", "を引き合いに出す；を引用する",
			"を修正する；を緩和する", "（を）誇張する；を強調する", "破裂する；（...を）突然始める（into）", "をぞくぞくさ せる；わくわくする", "を超える；に勝る", "特権，特典",
			"自由（≒freedom）；解放；気まま", "繁栄", "遺産", " （米国などの）議会；会議", "（英国などの）議会；国会議員団", "（経済）基盤；インフラ", "側面，局面；次元；寸法",
			"部分；１人前；割り当て", "栄養補助剤；補足", "食欲；欲求", "気質，気性；機嫌；かんしゃく", "（気まぐれな）好み；空想；思いつき", "錯覚，思い違い；幻想", "疲労（≒exhaustion）",
			"ストレス；圧力；強調", "危険（要素）；偶然", "感染（症）", "飢饉；（食糧・物資の）ひどい不足", "混沌，大混乱", "苦悩；苦痛；困窮", "恥；残念なこと", "（集合的に）牛",
			"捕食動物；略奪者", "荒野", "（日）陰；明暗の度合い；日よけ", "修道士，僧（⇔nun 修道女，尼）", "聖職者", "葬式", "移り変わり；過渡期", "循環；流通；（新聞・雑誌の）発行部数",
			"青年", "方程式；（the ～）同一視", "特許（権）；特許品", "隠喩；比喩", "物語，話", "同意，承諾", "尊厳；威厳", "関係がある（⇔irrelevant 関係のない）；適切な",
			"十分な；適切な（⇔inadequate 不適切な）", "本物の（≒real, authentic）", "迅速な", "親 密な；密接な", "警戒して；敏速な", "保守的な；保守党の；控えめな",
			"無関心な（≒uninterested）", "（...にとって ）異質の（to）；外国の", "無作為の；手当たり次第の", "微妙な；希薄な", "適度な；穏健な", "多様な", "極地の；電極の",
			"（しばしばA-）北極の（⇔antarctic 南極の）", "酸性の；酸っぱい；辛辣な", "化粧の，美容の", "絶滅した；廃止された", "精神の（⇔material 物質の）；霊的な", "意味のある",
			"機械の；機械的な", "活動的な；動的な（⇔static 静的な）", "を高める；を増加させる", "を強化する", "を蓄積する；積もる", "をはぐくむ；を養成する", "（人）を慣れさせる",
			"一致する；文通する", "を配属する；を割り当てる", "を規制する；を調整する", "を侵害する；（規則）を破る", "をいらいらさせる", "を侮辱する（≒affront）",
			"を減らす；減少する（≒decrease）", "を除外する（⇔include  を含む）", "から（金品を）奪う", "から（権利などを）奪う", "を置く；を預ける；を堆積させる",
			"をねじる，ひねる；を歪曲する", "を混ぜる；を調和させる", "に着手する；に乗る；に乗せる；増える", "を投げる", "を投じる；に役を当てる", "を投棄する；を落とす", "を予期する",
			"を評価する；を査定する", "を宣言する；を発音する", "（語）をつづる；という語になる", "を描く；を演じる", "を驚かす", "（光・音など）を出す", "咳をする", "歩き回る；それる，はぐれる",
			"漂う；さまよう；を押し流す", "をやめる；終わる", "の根底にある", "を構成する", "（好ましくない手段に）訴える", "を装飾する", "を改革する", "を征服する；を克服する",
			"固執する；続く", "動機（付け）；報奨金", "直観（力），直感", "衝動；刺激", "空想；幻想；幻想的作品", "運命", "美徳；長所；効能", "賛辞；表敬", "記念日", "ミツバチの巣；群衆",
			"託児所；苗床", "【米】寮", "美術館，画廊；回廊", "製造工場；製粉所；粉ひき機", "生産（高）；出力；排出（量）", "関節；接合（部）", "段階；面", "（微）粒子；ほんのわずか",
			"コラム；（新聞などの）欄；円柱", "余白；差；利ざや", "割れ目；鋭い音", "散らかった状態；混乱状態", "（試合などの）観客", "獲物；犠牲者", "灌漑", "流動体，液体", "大草原",
			"（動産・不動産などの）財産；私有地", "（小説などの）筋；陰謀", "領域；領土", "締め切り", "世論調査（＝opinion poll）；投票（数）", "国勢調査；交通調査", "論争",
			"戦闘；対立", "総意；（意見の）一致", "（国家間の）条約；協定", "治療（法）；治療薬；解決法", "勝利；勝利の喜び；偉業", "有能な；適任の；満足できる", "すばらしい；才能にあふれた；きらめく",
			"賢明な；実用的な；顕著な", "寛大な；気前のよい（⇔stingy けちな）；豊富な", "勇敢な（⇔cowardly 臆病な）；見事な", "楽観的な（⇔pessimistic 悲観的な）",
			"受動的な；消極的な", "厳しい；ざらついた", "醜い；険悪な", "感覚の", "口頭の", "気まずい；ぎこちない；面倒な", "中立の；はっきりしない", "漠然とした", "緊急の", "避けられない",
			"具体的な（⇔abstract 抽象的な）；有形の", "豊富な", "神聖な（≒holy）；宗教的な", "卓越した；目立つ", "密集した，密度の高い；（霧などが）濃い", "重大な；深い；難解 な",
			"に取り組む；と話をつける", "をささげる；を献呈する", "あえて［思い切って］～する", "（を）加速する，促進する", "を伝える；を送る", "に負担をかける；を緊張させる；を漉す",
			"を引きつける；（人）を～する気にさせる", "をおもしろがらせる；を楽しませる", "をむかつかせる；に愛想を尽かせる", "をだます；不正をする", "を限定する；（通例受身形で）閉じ込められる",
			"を隠す（≒hide）；を秘密にする", "許す；を免除する", "を捨てる；を解雇する", "に有罪を宣告する", "通勤［通学］する", "（と）ささやく", "薄れる；衰える",
			"飢える；（...を）渇望する（for）；を飢えさせる", "消える（≒disappear）", "（液体）を流出させる；（液体が）流れ出る", "を浸す；を突っ込む；下がる", "を 押しつぶす；を弾圧する",
			"爆発する；急増する；を論破する", "を怖がらせる；を脅かす", "を活用する；を搾取する", "を選出する", "に備えつける；を（...のために）装備する（for）", "を実現させる；を果たす；を満たす",
			"（log onで）ログオンする；を記録する", "を受け継ぐ；を引き継ぐ", "を提出する；（submit oneselfで）従う；（...に）屈服する（to）", "を更新する；を再生する",
			"を複製する；を再生する；繁殖する", "繁栄する；繁茂する；を振りかざす", "繁栄する；成 功する；繁茂する", "をこぼす；こぼれる", "をまき散らす；四散する", "（都市などが）不規則に広がる",
			"普及している；支配的である；打ち勝つ", "知性；（the ～）知識人", "礼儀正しさ；好意；優遇", "姿勢；心構え", "社会学", "動機", "合図；手掛かり", "公共事業；実用性",
			"雑用；日課；嫌な仕事", "（通例 ～s）穀物；シリアル（穀物加工食品）", "繊維（質）；本質；精神力", "摂取量；受け入れ数", "香り；香水；気配", "風味；特色", "混合（物）", "比率",
			"相当する物［人］", "小区画の土地；継ぎ；はり薬", "群れ；群集", "歩行者", "司書，図書館員", "下書き；為替手形；すき間風", "方法；公式；製法", "商品；有用なもの",
			"（通例 ～s）資産；価値のあるもの；利点", "通貨；普及", "潮（の干満）；動向", "妊娠中絶", "損害（の程度）；死者数；通行料", "（刑）罰；罰金", "森林伐採", "細菌；微生物",
			"発生，勃発", "流行病；蔓延", "症候群；...現象", "直売店；はけ口；【米】（電気の）コンセント（≒【英】socket）", "香水，香料", "歓迎会；受付；受領",
			"受け取る人；（臓器などの）被提供者", "熱心な；鋭敏な；激しい", "そこそ この；きちんとした；上品な", "穏やかな；軽い", "謙虚な；質素な；身分が低い", "高貴な；堂々とした",
			"利己的な（≒self-centered）", "残酷な；厳しい", "ばかげた；法外な", "耳が聞こえない（≒hard of hearing）", "感謝している", "入念な；凝った",
			"粗い；大まかな；乱暴な", "苦い；厳しい；辛辣な；怒りっぽい", "急進的な；根本的な", "集団の，共同の", "外来の；異国風の", "（傾斜が）急な；急激な；法外な",
			"浅い（⇔deep 深い）；浅薄な", "（...と）平行の（to）；類似した", "十分にありそうな", "絶対的な（⇔relative 相対的な）", "美的な；美学の",
			"進行する；（...を）続行する（with）", "花が咲く；栄える", "を主張する", "と確信する；（を）賭ける", "を誇る；（を）自慢する", "に（...を）切に頼む（for）；（を）懇願する",
			"妥協する；を危うくする", "（を）尋ねる", "叫ぶ，怒鳴る", "をいじめる；を脅す", "（を）降りる（⇔ascend 上がる）；受け継がれる", "はう；ゆっくり進む", "かがむ；傾く；をもたせかける",
			"を回転させる；（糸）を紡ぐ；回転する", "溺死する；を水浸しにする", "を分割する；分裂する", "を復活させる；復活す る", "ため息をつく", "控える", "（を）掃く；を一掃する；通過する",
			"編み物をする；を結合する", "を詰め込む；詰め込み勉強をする", "を消化する；を理解する；を要約する", "を抑える；を抑圧する", "の気分を害する；（に）違反する",
			"補償する（≒make up）；に償う", "を悪化させる；を合成する；を混合する", "から成る；を構成する", "を移植する； を移住させる", "を暴く；を発掘する", "を取り出す；を抜粋する；を引用する",
			"を募る；に新人を補充する", "に権利を与える；に題名を付ける", "を任命する；を指定する", "を設置する；を就任させる", "を施行する；を（...に）強制する（on / upon）", "を実行する",
			"を（巧みに）操る；を改ざんする", "を精製する；を洗練する", "を獲得する，達成する；に達する", "探究", "態度，見解；見通し；眺め", "前提；（～s）（建物を含めた）構内", "統合；結束；一貫性",
			"織物 ；構造", "（議論などの）筋道；糸", "職人；工芸家", "彫刻（作品）", "球体；領域；天体", "（道路などの）カーブ；曲線", "人物の紹介；横顔；輪郭", "指紋", "（判断・評価の）基準",
			"高度，標高", "授業料（＝tuition fees）；（個人）指導", "杭；賭け金；利害関係", "知人；面識；知識", "会話；講演", "感謝（の気持ち）", "崇拝；賛美", "用心；警告",
			"恐怖；強い嫌悪；嫌な物［人］", "腐敗（した状態）；衰退", "欠陥；不足", "（～s）軍隊；集団", "墓；（the ～）死", "牧場；【米】大農場", "共和国；共和制", "【米】郡；【英】州",
			"【米】小別荘；小さな家", "商業；貿 易", "不況；後退", "絶望", "噴霧（液）；噴霧器", "同情", "子孫，子；成果", "皮質；樹皮", "名声", "価値がある；立派な",
			"妥当な（⇔invalid 妥当でない）；有効な", "徹底的な；全くの", "途方もない，莫大な；すばらしい", "経験的な；経験主義の", "二次的な；中級の", "その後の", "生まれながらの；固有の",
			"室内の；内部の（⇔exterior 外 部の）", "裸の；ありのままの", "無罪の（⇔guilty 有罪の）；無邪気な；無知の", "繊細な；扱いにくい；もろい", "あ いまいな", "壊れやすい；虚弱な",
			"ひどい；嫌な；恐ろしい", "より劣った（⇔superior よりすぐれた）", "恥じて", "中世の；時代遅れの", "厳しい；いかめしい", "張り詰めた，緊張した", "帝国の；皇帝の",
			"壮大な；見事な", "を統 合する；融合する", "を取り入れる；を法人にする；合併する", "を利用する（≒make use of）", "を修正する；を改正する", "を長引かせる", "を少なくする；減る",
			"をかき回す；を揺り動かす", "を引きずる；ぐずぐずする", "（を）磨く", "を［から］取り去る；を裸にする", "を押し込む；を絞る", "を捨て去る；（光など）を放つ；（涙・血）を流す",
			"（plug inで）を電源に差し込む；を差し込む", "を歪める；歪む", "を混乱させる；を分裂させる", "を荒らす；を困惑させる", "を悪化させる；悪化する（≒deteriorate）",
			"を廃止する（≒do away with）", "を取り戻す", "を及ぼす；を行使する", "に先行する；に優先する", "遅れる；徐々に弱まる", "（...と）会話をする（with）",
			"（声）を発する；（考えなど）を述べる", "の要点を述べる；の輪郭を描く", "順応する；一致する", "を指定する；を任命する", "に自信を持って言う；を保証する", "を安心させる", "を慰める",
			"を引き起こす；を説得する", "に義務づける；に恩恵を施す", "に強いる", "を引き起こす；を刺激する", "【米】を風呂に入れる；を浸す", "出血する", "（を）巡航する；巡回する",
			"急上昇する；空高く飛ぶ", "を象徴する；を記号で表す", "を理解する", "議定書", "分野", "指標；索引", "（商）取引；（人と人との）交流", "断片", "わずか（≒bit）；一部；分数",
			"虫；病原体；盗聴器；欠陥", "細菌；胚", "診断；判断", "（...の）妄想（with）；強迫観念", "悪夢；不安感", "逆説；矛盾", "皮肉", "悲しみ", "最大限（⇔minimum 最小限）",
			"過剰，超過", "国境；（the ～）【米】辺境地；最先端", "避難（所）；保護", "【英】木材（≒【米】lumber）；樹木", "奴隷制度；苦役", "（社会の）階層制；支配層",
			"（官庁の）局；事務局", "監督者；指導教員", "配偶者", "反逆者", "気晴らし；娯楽", "祝宴；大ごちそう；楽しみ", "洗面器；水たまり；流域", "下水", "（集合的に）景色；背景", "墓",
			"目印；画期的な出来事", "記念碑；遺跡；金字塔", "（人・動物の）肉；果肉", "衣服", "ちらりと見えること", "輝き；白熱；幸福感", "優美；分別；恩寵", "誠実な；心からの",
			"大胆な；厚かましい", "飼いならされた", "もろい", "裸の", "（...に）免疫を持つ（to）；免れた", "慢性の（⇔acute 急性の）；長引く", "徐々の", "乏しい；珍 しい",
			"有毒な；中毒性の", "偶然の", "（...にとって）無関係の（to）；見当違いの", "ささいな", "不可欠な（⇔dispensable なくてもすむ）", "原産の，先住の", "有史以前の；旧式な",
			"神聖な；信仰心の厚い", "小売の（⇔wholesale  卸売りの）", "大都市の，首都圏の", "単純な；率直な", "鮮やかな；生き生きとした", "際立った；未払いの", "を豊かにする",
			"を引き受ける；を保証する；に着手する", "を収容する；を（...に）適応させる（to）", "を集める；を組み立て る；集まる", "を具現する；を統合する", "を織る；を作り上げる",
			"を回収する；（データ）を呼び出す", "（手）をたたく；（に）拍手する", "を引っかく；を中止する", "を消す", "を縫う；縫い物をする", "しがみつく；くっつく", "（を）辞任する；を放棄する",
			"をびっくりさせる（≒surprise）", "を呼び起こす", "を明確にする", "（を）告白する", "（を）祈る", "を許容する，我慢する（≒put up with）", "をうらやむ",
			"（revenge oneselfまたは受身形で）復讐する", "出発する；（...から）それる（from）", "を追い抜く；に追いつく（≒catch up with）；を襲う",
			"を侵略する；を侵害する；に殺到する", "の内部に入る；（を）貫く；（に）進出する", "を同封する；を取り囲む", "漏れる；を漏らす", "を紅潮させる；を水で流す；紅潮する", "輝く；際立つ",
			"（火山が）噴火する；勃発する", "を染める；染まる", "を止める；止まる", "を停職［停学］処分にする；を中断する", "を上回る", "（を）操縦する；を（...へ）向ける（to）",
			"航行する ；進路を示す", "と矛盾する；に反対意見を言う", "と主張する；競う", "を溶かす；を分解する；溶ける", "努力する；争う", "遺産", "うわさ", "韻文（⇔prose 散文）；詩",
			"原稿；写本", "台本；筆跡", "散文（⇔verse 韻文）；退屈な話", "（新聞などの）見出し", "直径", "真空；空虚", "炎；情熱", "水分；湿気", "浸食；衰退", "半島",
			"自殺；自殺的行為", "（宗教・道徳上の）罪；愚かなこと", "禁忌，タブー", "激怒；猛威", "強欲", "退屈", "悲惨；苦難", "疫病；（害虫などの）異常発生", "孤児", "肝臓",
			"跡；手がかり；小道", "（座席間などの）通路", "洗濯（物）；クリーニング店", "商品", "買い得品；取引；契約", "（～s）歳入（⇔expenditures 歳出）；（～s）収益",
			"赤字，不 足；欠陥", "素人，アマチュア（⇔professional プロ）", "学部学生", "大使；使節", "戦士", "戦争（行為）；闘争", "植物学；（一地方の）植物", "人類学",
			"イデオロギー，思想傾向", "自発的な（⇔compulsory 強制的な）；無償の", "自然発生的な；無意識的な", "故意の；慎重な", "目立つ", "透明な；明快な", "表面的な", "空洞の；空虚な",
			"特有の；特異な", "部分的な；不公平な；特に好きな", "きちんとした；見事な", "薄暗い；ぼんやりした", "代わりの（≒alternative）；交互の", "（日常的に）当たり前の",
			"嫉妬深い；用心深い", "敵意のある；敵の", "熟した；成熟した", " 妊娠した；（...で）満ちている（with）", "肥沃な（⇔infertile，barren 不毛の）", "猛烈な；どう猛な",
			"徹底的な", "膨大な", "最高の", "（...で）秀でている（in / at）；に勝る", "膨張する，腫れる；を膨らませる", "跳ねる；反射す る；を弾ませる", "（を）歩き回る",
			"はぐれる；迷う", "（他国へ）移住する", "（を）つぶやく；ぶつぶつ（不平を）言う", "（を）ささやく；ざわめく", "くすくす笑う", "をむせさせる；を詰まらせる；むせる",
			"（...に）眉をひそめる（upon / at）", "うなる，ほえる", "震える", "震える；揺れ動く", "（顔・ひげなど）をそる；を削減する", "（を）誤解する", "をなだめる；を和らげる",
			"を誘惑する", "をばかにする（≒make fun of）；をからかう", "（を）からかう；を いじめる", "を軽蔑する（≒look down on）", "を無視する；を軽視する",
			"をうっかり表す；を裏切る", "（...を）熱望 する（to）", "をつかむ；を奪い取る；を没収する", "を持って来る，連れて来る", "（を）こする；を塗る", "ぱたぱたと動く；羽ばたく",
			"（を）突っ込む；没頭する；陥る", "を挿入する", "（dispose ofで）を処分する", "に耐える", "を妨げる", "（を）再開する；を取り戻す", "を統合する", "必需食品；主要産物",
			"大豆", "芽；つぼみ", "植物；植生", "手足", "しわ；折り目", "感情；感傷", "深い悲しみ", "呪い；悪態", "拷問；苦痛（の種）", "慈悲；幸運", "臆病者",
			"前任者（⇔successor 後継者）；前のもの", "精神科医", "論文；命題，テーゼ", "突然変異", "糖尿病", "銃弾", "集団；（植物の）房，束", "盾，防御物", "器具；歯車；ギア",
			"船舶；容器；脈管", "戦術；策略", "崩壊；（神経）衰弱；故障", "再会（の集い）；再結合", "結び目", "宇宙探査用ロケット；精査", "放射能，放射線", "錠剤；平板", "蒸気；気体",
			"温度計，体温計", "署名；特徴", "三角形", "幾何学", "偉業；妙技", "拍手（喝采）", "栄光；壮観", "勤勉な；入念な", "まじめな，熱心な", "（...に）忠実な（to）",
			"頑固な（≒obstinate）；不屈の", "厳しい；硬直した", "硬直した；堅い", "臆病な", "（何もせずに）ぶらぶらしている", "ばかげた；口のきけない；無言の", "肥満した",
			"障がいのある；障がい者用の", "不器用な；扱いにくい", "時間を守る", "ばかげた；不合理な", "不安な；落ち着かない；ぎこちない", "不快な；意地悪な", "いたずらな", "きちんとした；相当の",
			"決定的な；断固とした", "真っすぐな；正直な", "垂直の（⇔horizontal 水平な）；縦方向の", "陰気な；薄暗い；悲観的な", "人目につかな い；不明瞭な", "骨董の；古風な",
			"唯一の；単独の；独占的な", "純然たる，真の；すごい", "すばらしい；驚くべき", "すばらしい；立派な", "を心に抱く；を大切にする", "に栄養を与える；をはぐくむ",
			"を孵化させる；孵化する；をたくらむ", "を拡大する", "に（...を）備え付ける（with）", "（...に）ふける（in）；を甘やかす", "（...に）屈する（to） ；を放棄する；を明け渡す",
			"ひざまずく", "（...に）つまずく（on / over）", "しおれる；衰える；を弱らせる", "忍び込む；のろのろ進む；はう", "痛む；（...を）切望する（for）",
			"を待つ（≒wait for）", "を予知する", "を照らす；を解明する", "をひどく恐れる", "を描く", "を意味する；重要である", "（を）誓う；ののしる",
			"を指図する；を書き取らせる；を決定づける", "を暗唱する；を詳述する", "登録する，入会する；を登録させる", "を実行する；を処刑する", "を偽造する；のふりをする", "を変装させる；を偽る",
			"を汚す；に着色する", "を縛る", "を（平手で）たたく", "を省く；を怠る", "（穀物など）をひく", "を徐々にむしばむ", "を破産させる", "（火・光など）を消す；を全滅させる",
			"を修繕する；を改善する", "（人）を（...のことで）祝う（on）", "証明書；免許状", "百科事典", "伝記", "傑作", "詩歌；韻", "手段；資力", "鋳型；性質", "範囲；余地",
			"（the ～）（...の）大半（of）；かさ；大量", "些細なこと；少量（≒a little）", "錠剤", "（薬の）服用量；放射線量", "血管；静脈（⇔artery 動脈）；特質", "におい；気配",
			"巡礼者", "行い", "【英】車両；立ち居振舞い；輸送；馬車", "いたずら", "虐殺；畜殺", "急ぐこと", "（のどの ）渇き；渇望", "君主制；君主国", "治世；統治",
			"相続人；（...の）後継者（to）", "許し", "法律；立法", "（the C-）内閣；戸棚", "病棟；行政区", "余剰；黒字", "計算；算数", "水銀（≒quicksilver）；（M-）水星",
			"独占（権）", "不和；摩擦", "衝突", "融合；連立", "大発見，飛躍的進歩", "壮観；見世物；【英】（～s）眼鏡", "高名な；傑 出した", "注目に値する；著名な",
			"悪名高い（≒infamous）", "義務的な", "～しがちな；受けやすい；責任がある", "～する傾向がある；傾いた", "静的な（⇔dynamic 動的な）；停滞した",
			"無限の（⇔finite 有限の）；無数の", "永遠の； 不変の", "激しい；鋭い；急性の（⇔chronic 慢性の）", "突然の", "素早い", "かすかな", "優しい；柔らかい；微妙な",
			"湿気のある", "湿った", "腐った；不快な；堕落した", "酸っぱい；不機嫌な；不愉快な", "痛い；腹が立って", "どう猛な；容赦のない", "天然の，未精製の；粗野な", "おおよその",
			"中級の；中間の", "職業の", "男らしい", "女らしい", "余分な；不必要な", "最大限の", "（を）熟考する；を予想する", "（を）熟考する", "瞑想する；をもくろむ", "（を）思いつく",
			"（を）推測する；投機する", "と推定する；を前提とする", "を宣言する；を証明する", "を公表する", "を誓う；を担保にする", "（と）叫ぶ", "（...を）予約購読する（to）",
			"（を）悼む；（を）嘆く", "に憤慨 する", "（を）嘆き悲しむ；を後悔する", "あえぐ；（...を）渇望する（for）", "（を）吸う", "を浸す；浸る", "を（ある状態に）する；を与える",
			"回転する；循環する；を回転させる", "を貫く，（穴）を開ける；を洞察する", "を彫る；を切り開く", "（注意など）をそらす；を迂回させる", "を追放する；を吐き出す", "を暴行する；を攻撃する",
			"侵害［侵入］する", "（受身形で）（...に）凝る，（...の）中毒になる（to）", "同時に起こる；一致する", "（を）上がる（⇔descend 下りる）", "殺到する；急騰する",
			"蒸発する；消散する；を蒸発させる", "期限が切れる", "を発酵させる；発酵する", "（を）合併する；融合する；を融合させる", "を建てる；を直立させる", "に恩恵を与える；に感謝する",
			"名声；（形容詞的に）名声のある", "（the ～）貴族（社会）；（the ～）支配階級", "政治家（≒statesperson）", "【米】（しばしばS-）上院議員", "（宗教上の）信条",
			"活力；迫力", "落胆；狼狽", "憂うつ", "苦痛；苦悩", "苦悩", "良心", "軽蔑；恥辱", "軽蔑；軽蔑の対象", "無感動", "織物；繊維（産業）",
			"（左右）対称（⇔asymmetry 非対称）；調和", "（the ～）瀬戸際；端", "虫歯（の穴）；空洞", "賄賂", "暴動", "亡命（者）；（国外）追放", "考古学", "標本；実例",
			"装飾（品）", "器具一式；機構", "欠点；傷", "日食，月食；（名声などの）失墜", "天文学", "航空（学）", "速度", "混雑", "アンケート", "寄生虫", "職員，人員",
			"（the ～）出現，到来", "しるし；代用硬貨；商品券", "保険料；プレミア", "思慮分別のある", "（...に）用心深い（of）", "（状況などが）暗い；（表情が）険しい", "厳粛な ；真剣な",
			"（...に）懐疑的な（of / about）", "疑わしい；疑って", "無駄な；うぬぼれた", "無謀な；（...を）顧みない（of）", "無慈悲な；断固とした；無茶な", "雄弁な；説得力のある",
			"激怒した；猛烈な", "疲れ果てた；（...に）う んざりした（of）", "悲観的な（⇔optimistic 楽観的な）", "冷笑的な", "邪悪な；いたずらな",
			"驚くべき；奇妙な；単 数の（⇔plural 複数の）", "異様な（≒bizarre）", "文字どおりの；散文的な", "明白な（⇔implicit）；率直な", "暗黙の（⇔explicit）；内在する",
			"ほっそりした；わずかな", "総計の；甚だしい；粗野な", "紫外線の", "空間の", "空いている", "広々とした；雄大な", "十分すぎるほどの；広い", "裕福な；豊富な", "を推論する",
			"を理解する；を識別する", "を主張する", "の原因を（...に）帰する（to）；を（...の）作と認める（to）", "（薬など）を処方する；を規定する", "（...に）従う（with）；応じる",
			"（abide byで）に従う；を我慢する；住む", "（...に）嘆願する（with）；（を）弁護する；申し立てる", "（を）説教する", "に興味を持たせる；陰謀を企てる",
			"を（...と）一致させる（with）；を和解さ せる", "（...に）介入する（in）；介在する", "を制止する；を規制する", "の自尊心を傷つける", "を非難する",
			"を 非難する；（受身形で）有罪を宣告される", "に反抗する；を拒む", "（...に）反逆する（against）；むかつく", "を損なう", "（害など）を負わせる", "の価値を下げる；を降格する",
			"悪化する；を悪化させる", "を堕落させる；を買収する；堕落する", "を汚染する；を堕落させる", "を抑圧する；を悩ませる", "を押しつける；押す", "（...に）乗り出す（on）； 乗船［搭乗］する",
			"を点検する；を視察する", "を呼びつける", "（を）証言する", "を迫害する；を苦しめる", "に強要する", "（抑えていたもの）を爆発させる", "を解放する", "に授ける；に寄贈する",
			"精査；監視", "類推；類似", "没頭；先入観", "回想", "うぬぼれ", "誤った考え；虚偽", "偽善", "厄介（なこと［人］）", "（青少年の）非行，犯罪", "人質", "（民事）訴訟",
			"【米】弁護士；代理人", "令状；十分な根拠；証明書", "証言；証拠", "（陪審の）評決；評価", "（通例 ～s）制裁；認可", "迷信", "民話；民俗学", "逸話", "修辞（法）；美辞麗句",
			"露店；失速", "部分", "合成；総合（⇔analysis 分析）", "結束；結合", "遺伝；世襲", "大災害；破局", "窮状", "ひとりでい ること；孤独", "厳しい試練", "暴政；専制国家",
			"検閲", "衛生（状態）；健康法", "【米】（政策上の）主義；教義", "外交（的手腕）", "実体", "君主；【英】ソブリン金貨", "本物の；信頼できる", "合法的な；妥当な", "理解できる",
			"生来の", "独創的な；利発な", "複雑な", "均質の（⇔heterogeneous 異質の）", "単調な", "絶え間のない", "ひっきりなしの；永続的な", "差し迫った", "もっともらしい",
			"恣意的な", "予備の，準備の", "（...が）欠けている （in）（≒lacking）", "（...より）下位の（to）；副次的な", "封建時代［制度］の；封建的な", "廃れた",
			"致命的な；死すべき（⇔immortal 不死の）", "金銭的な；金融の", "浪費する；法外な", "めまいがする；当惑した", "青少年の", "匿名の", "互換性のある；矛盾しない；気が合う",
			"至る所にある", "神の；神にささげる", "しらふの；節度のある", "熱心な"
	};
}
